# Generated by Django 2.2.6 on 2019-11-02 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=24)),
                ('last_name', models.CharField(max_length=24)),
                ('company', models.CharField(choices=[('GIC', 'Global inti Corporatama'), ('SMG', 'Satya Mitra Graha')], default='GIC', max_length=3)),
                ('division', models.CharField(choices=[('DIR', 'Director'), ('MNG', 'Manager'), ('SUP', 'Supervisor'), ('STF', 'Staff'), ('PRO', 'Programmer'), ('AND', 'Android Devloper'), ('SYS', 'System Administrator'), ('NOC', 'Network Oprations Center'), ('HRD', 'Human Resources Departement'), ('FIN', 'Finance'), ('SLS', 'Sales'), ('TEC', 'Technician'), ('LOG', 'Logistic'), ('REC', 'Receptionist'), ('OBY', 'Office Boy'), ('CRI', 'Courier'), ('DRI', 'Driver')], default='STF', max_length=3)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=256)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
