# Generated by Django 2.2.6 on 2019-11-05 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
    ]
