# Generated by Django 2.2.6 on 2019-11-05 06:01

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('node1', '0002_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=128)),
                ('street', models.CharField(max_length=128)),
                ('postal', models.IntegerField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
            options={
                'ordering': ['address'],
            },
        ),
    ]
